[server]
headless = true                       # Set to true to deploy on a remote server
port = 8501                           # Default port for Streamlit
enableCORS = false                    # Disable CORS (important when deploying)

[global]
# Enable/disable wide mode for Streamlit's layout
wideMode = true